/*
 * Copyright Debezium Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package io.debezium.connector.yashandb;

import java.sql.SQLException;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;

import io.debezium.config.Configuration;
import io.debezium.connector.yashandb.util.TestHelper;
import io.debezium.pipeline.AbstractMetricsTest;
import io.debezium.util.Testing;

public class YashanDbMetricsIT extends AbstractMetricsTest<YashanDbConnector> {

    private static YashanDbConnection connection;

    @Override
    protected Class<YashanDbConnector> getConnectorClass() {
        return YashanDbConnector.class;
    }

    @Override
    protected String connector() {
        return Module.name();
    }

    @Override
    protected String server() {
        return TestHelper.server();
    }

    @Override
    protected Configuration.Builder config() {
        return TestHelper.defaultConfig()
                .with(YashanDbConnectorConfig.SNAPSHOT_MODE, YashanDbConnectorConfig.SnapshotMode.INITIAL);
    }

    @Override
    protected Configuration.Builder noSnapshot(Configuration.Builder config) {
        return config.with(YashanDbConnectorConfig.SNAPSHOT_MODE, YashanDbConnectorConfig.SnapshotMode.NO_DATA);
    }

    @Override
    protected void executeInsertStatements() throws SQLException {
        connection.execute("INSERT INTO dbz.customer VALUES (NULL, 'Billie-Bob', 1234.56, TO_DATE('2018-02-22', 'yyyy-mm-dd'))");
        connection.execute("INSERT INTO dbz.customer VALUES (NULL, 'Bruce', 2345.67, null)");
        connection.execute("COMMIT");
    }

    @Override
    protected String tableName() {
        return "DBZ.CUSTOMER";
    }

    @Override
    protected long expectedEvents() {
        return 2L;
    }

    @Override
    protected boolean snapshotCompleted() {
        return true;
    }

    @BeforeAll
    static void beforeAll() throws Exception {
        TestHelper.dropTestUser();
        io.debezium.connector.yashandb.util.TestHelper.createTestUser();
        connection = TestHelper.connectedConnection();
        connection.setAutoCommit(false);
        TestHelper.dropAllTables();
        io.debezium.connector.yashandb.util.TestHelper.createYStreamServer();
        io.debezium.connector.yashandb.util.TestHelper.stopYStreamIfRunning();
        TestHelper.dropTable(connection, "dbz.customer");

        String ddl = "create table dbz.customer (" +
                "  id numeric(9,0) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 101) not null, " +
                "  name varchar2(1000), " +
                "  score decimal(6, 2), " +
                "  registered timestamp, " +
                "  primary key (id)" +
                ")";

        connection.execute(ddl);
        connection.execute("ALTER TABLE dbz.customer ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS");

    }

    @AfterAll
    static void afterAll() throws SQLException {
        if (connection != null) {
            TestHelper.dropTable(connection, "dbz.customer");
            connection.close();
        }
    }

    @BeforeEach
    void before() throws Exception {
        connection.execute("delete from dbz.customer");
        TestHelper.addYStreamTables("customer");
        setConsumeTimeout(3, TimeUnit.SECONDS);
        initializeConnectorTestFramework();
        Testing.Files.delete(TestHelper.SCHEMA_HISTORY_PATH);
    }
}
